# Logs:
debug: false  # Debug mode
weave_project: "gpt-translate"  # Weave project
silence_openai: true  # Silence OpenAI logger

# Translation:
language: "ja"  # Language to translate to
config_folder: "./configs"  # Config folder
replace: true  # Replace existing file
remove_comments: true  # Remove comments
do_translate_header_description: true  # Translate the header description
max_concurrent_calls: 7  # Max number of concurrent calls to the LLM

# Files:
input_file: "docs/intro.md"  # File to translate
out_file: " intro_ja.md"  # File to save the translated file to
input_folder: ./docs/  # Folder to translate
out_folder: ./docs_translated/  # Folder to save the translated files to
limit: null  # Limit number of files to translate (useful for testing)

# Model:
model: "gpt-4o"
temperature: 1.0
max_tokens: 16000
